spring.application.name=notes-api
spring.config.import=optional:file:.env[.properties]
server.address=127.0.0.1
server.port=8080
spring.datasource.url=jdbc:postgresql://127.0.0.1:${DB_PORT:5432}/${DB_NAME:notes}
spring.datasource.username=${DB_USER:notes}
spring.datasource.password=${DB_PASSWORD}
spring.sql.init.mode=always
spring.jackson.deserialization.fail-on-unknown-properties=true
server.error.include-message=never
server.error.include-stacktrace=never
app.jwt.secret=${JWT_SECRET}
app.bootstrap.username=${APP_USERNAME:student}
app.bootstrap.password=${APP_PASSWORD}
